<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Wordscope</title>
    <link rel="stylesheet" href="/css/home.css">
</head>

<body>
<div class="container">
    <div class="header">
        <div class="header-title">Wordscope</div>
    </div>

    <div class="content">
        <div class="tile-group">
            <div class="tile">
                <div class="tile-title">Ascii Sum</div>
                <p class="tile-description">Sums the numerical value of each character in a string</p>
                <a href="/asciiSum">Calculate sums</a>
            </div>

            <div class="tile">
                <div class="tile-title">Word Extraction</div>
                <p class="tile-description">Finds the words embedded in another word, or a word jumble</p>
                <a href="/extractWords">Extract words</a>
            </div>
        </div>
    </div>
    <div class="footer">🔡🔬</div>
</div>
</body>
</html>